<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-S58JSNEH" failures="1" tests="6" name="Surefire test" time="104.587" errors="0" timestamp="2025-05-15T19:44:16 IST">
  <testcase classname="com.org.main.tests.ErrorValidationsTest" name="LoginErrorValidation" time="0.854"/>
  <testcase classname="com.org.main.tests.ErrorValidationsTest" name="ProductErrorValidation" time="13.037">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.org.main.tests.ErrorValidationsTest.ProductErrorValidation(ErrorValidationsTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
  <testcase classname="com.org.main.tests.SubmitOrderTest" name="submitOrder" time="28.04"/>
  <testcase classname="com.org.main.tests.SubmitOrderTest" name="submitOrder" time="19.652"/>
  <testcase classname="com.org.main.tests.SubmitOrderTest" name="orderHistoryTest" time="6.958"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.408"/>
</testsuite> <!-- Surefire test -->
